/*
 * Bundle types constants
 */

import type { BundleConfig, BundleType } from "@/features/bundles";

/**
 * Name patterns for bundle name generation
 */
export const BUNDLE_NAME_PATTERNS: Record<BundleType, string[]> = {
    FIXED_BUNDLE: [
        "Product Bundle",
        "Essential Pack",
        "Complete Set",
        "Value Bundle",
        "Combo Deal",
        "Starter Kit",
        "Premium Pack",
        "Classic Bundle",
        "Signature Set",
        "Ultimate Collection",
        "Power Pack",
        "Complete Package",
        "All-in-One Bundle",
        "Essentials Box",
        "Deluxe Set",
        "Core Collection",
        "Foundation Pack",
        "Total Package",
        "Full Set",
        "Comprehensive Bundle",
    ],
    BUY_X_GET_Y: [
        "Buy More Save More",
        "Multi-Buy Deal",
        "Quantity Deal",
        "Bulk Offer",
        "Volume Offer",
        "Buy X Get Y Deal",
        "Quantity Discount",
        "Multi-Purchase Offer",
        "Stock Up Deal",
        "Bulk Buy Savings",
        "More for Less",
        "Quantity Savings",
        "Buy in Bulk",
        "Volume Purchase",
        "Multi-Item Deal",
        "Bulk Discount",
        "Purchase More Deal",
        "Multiple Buy Offer",
        "Quantity Bonus",
        "Buy Multiple Save",
    ],
    BOGO: [
        "BOGO Deal",
        "Buy One Get One",
        "Double Deal",
        "Two for One",
        "BOGO Offer",
        "Twin Pack Deal",
        "Double Up Offer",
        "2-for-1 Special",
        "Duo Deal",
        "Pair & Save",
        "Double Delight",
        "Two's Company",
        "Double Discount",
        "Get One Free",
        "Bonus Item Deal",
        "Double Value",
        "Twin Special",
        "Paired Savings",
        "Dual Deal",
        "Twofer Offer",
    ],
    VOLUME_DISCOUNT: [
        "Volume Discount",
        "Bulk Savings",
        "Wholesale Pack",
        "Quantity Discount",
        "Bulk Deal",
        "Volume Pricing",
        "Tiered Discount",
        "Bulk Buy Offer",
        "Quantity Breaks",
        "Volume Offer",
        "Scale Savings",
        "Bulk Purchase Deal",
        "Volume Savings",
        "Wholesale Discount",
        "Quantity Price Break",
        "Graduated Discount",
        "Tier Pricing",
        "Bulk Rate",
        "Volume Deal",
        "Quantity Tier",
    ],
    MIX_AND_MATCH: [
        "Mix & Match",
        "Build Your Bundle",
        "Custom Pack",
        "Pick & Save",
        "Create Your Own",
        "Choose Your Bundle",
        "Mix It Up",
        "Custom Selection",
        "Your Choice Bundle",
        "Build Your Own",
        "Mix & Save",
        "Pick Your Pack",
        "Customizable Set",
        "Choose & Combine",
        "Select & Save",
        "Personalized Bundle",
        "Curated Collection",
        "Flexible Pack",
        "Your Way Bundle",
        "Custom Combo",
    ],
    FREQUENTLY_BOUGHT_TOGETHER: [
        "Frequently Bought Together",
        "Perfect Pair",
        "Complete The Look",
        "Better Together",
        "Recommended Combo",
        "Popular Pairing",
        "Customer Favorite",
        "Goes Great With",
        "Commonly Combined",
        "Top Picks Together",
        "Best Sellers Bundle",
        "Popular Combo",
        "Fan Favorites",
        "Trending Together",
        "Smart Pairing",
        "Often Paired",
        "Bestseller Duo",
        "Top Combination",
        "Customer Choice",
        "Most Loved Pair",
    ],
} as const;

/**
 * Bundle type configurations
 */
export const BUNDLE_TYPES = {
    FIXED_BUNDLE: {
        label: "Fixed bundle",
        id: "FIXED_BUNDLE",
        slug: "fixed-bundle",
        description:
            "Group specific products into one package with a single discounted price.",
        features: [
            "Gift boxes or holiday sets.",
            "Full outfits (blazer + pants + shirt + shoes).",
            "Product bundles with accessories (phone + case + charger).",
        ],
        bundleImage: "/assets/fixed-bundle.svg",
        modalImage: "/assets/fixed-bundle-popup.png",
        namePatterns: BUNDLE_NAME_PATTERNS.FIXED_BUNDLE,
        comingSoon: false,
        hidden: false,
    },
    BUY_X_GET_Y: {
        label: "Buy X Get Y",
        id: "BUY_X_GET_Y",
        slug: "buy-x-get-y",
        description:
            "Buy a specific product to unlock a discount on a different product.",
        features: [
            "Cross-selling related items (Buy a laptop, get 30% off a mouse)",
            "Pairing accessories with main products (Buy a camera, get a memory card free)",
            "Strategic upsells (Buy skincare, get a travel bag 50% off)"
        ],
        bundleImage: "/assets/buy-x-get-y.svg",
        modalImage: "/assets/buy-x-get-y-popup.png",
        namePatterns: BUNDLE_NAME_PATTERNS.BUY_X_GET_Y,
        comingSoon: false,
        hidden: false,
    },
    BOGO: {
        label: "BOGO",
        id: "BOGO",
        slug: "bogo",
        description:
            "Buy one product, get another one free or discounted. Usually the same product or product type.",
        features: [
            "Classic promotions (Buy 1 Get 1 Free on t-shirts).",
            "Moving slow-selling inventory fast.",
            "Increasing order quantity without dropping unit price."
        ],
        bundleImage: "/assets/bogo.svg",
        modalImage: "/assets/bogo-popup.png",
        namePatterns: BUNDLE_NAME_PATTERNS.BOGO,
        comingSoon: false,
        hidden: false,
    },
    VOLUME_DISCOUNT: {
        label: "Volume discount",
        id: "VOLUME_DISCOUNT",
        slug: "volume-discount",
        description: "The more they buy, the bigger the discount. Applied to the same product.",
        features: [
            "Bulk purchases (Buy 3, save 10%; Buy 5, save 20%).",
            "Wholesale or B2B scenarios.",
            "Clearing stock or rewarding loyal customers."
        ],
        bundleImage: "/assets/volume-discount.svg",
        modalImage: "/assets/volume-discount-popup.png",
        namePatterns: BUNDLE_NAME_PATTERNS.VOLUME_DISCOUNT,
        comingSoon: false,
        hidden: false,
        proRequired: true,
    },
    MIX_AND_MATCH: {
        label: "Mix & match",
        id: "MIX_AND_MATCH",
        slug: "mix-and-match",
        description: "Choose any combination from products",
        features: ["Pick any 3 for $50", "Mix different categories"],
        bundleImage: "/assets/mix-match.svg",
        modalImage: "/assets/mix-match-popup.png",
        badge: { text: "Coming soon!", tone: "success" },
        namePatterns: BUNDLE_NAME_PATTERNS.MIX_AND_MATCH,
        comingSoon: false,
        hidden: true,
    },
    FREQUENTLY_BOUGHT_TOGETHER: {
        label: "Frequently bought together",
        id: "FREQUENTLY_BOUGHT_TOGETHER",
        slug: "frequently-bought-together",
        description: "Frequently bought together",
        features: ["Smart product suggestions", "AI-powered recommendations"],
        bundleImage: "/assets/frequently-bought-together.svg",
        modalImage: "/assets/frequently-together-popup.png",
        badge: { text: "Coming soon!", tone: "success" },
        namePatterns: BUNDLE_NAME_PATTERNS.FREQUENTLY_BOUGHT_TOGETHER,
        comingSoon: false,
        hidden: true,
    },
} as const satisfies Record<BundleType, BundleConfig>;
