# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "90639cf08512143558f29fdc47f10d98"
name = "Product Bundles 47"
handle = "product-bundles47"
application_url = "https://ferrari-entered-timer-call.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "bundles47.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_price_rules,write_script_tags,read_themes,write_themes,read_inventory,read_orders,read_customers,read_price_rules"
use_legacy_install_flow = false

[auth]
redirect_urls = ["https://ferrari-entered-timer-call.trycloudflare.com/auth/callback", "https://ferrari-entered-timer-call.trycloudflare.com/auth/shopify/callback", "https://ferrari-entered-timer-call.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
