# Avoid writing to toml directly. Use your .env file instead

name = "Product Bundles"
handle = "product-bundles-111"
client_id = "b1cd6f12e536f4d86d04231d69a1fb35"
application_url = "https://radius-product-bundles.vercel.app"
embedded = true
extension_directories = [ "./extension/extensions/**" ]

[app_proxy]
url = "https://radius-product-bundles.vercel.app/api/proxy"
subpath = "bundles"
prefix = "apps"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "bundlestesting-2.myshopify.com"

[webhooks]
api_version = "2026-01"

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true

[access_scopes]
scopes = "read_customers,read_orders,read_price_rules,read_products,read_themes,write_files,write_app_proxy,write_price_rules,write_products,write_publications,write_script_tags,write_discounts"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://radius-product-bundles.vercel.app/api/auth/callback",
  "https://radius-product-bundles.vercel.app/api/auth/oauth/callback"
]

[pos]
embedded = false

[product.metafields.app.bundle_ids]
type = "list.single_line_text_field"
name = "Bundle IDs"
description = "List of bundle IDs that include this product"

  [product.metafields.app.bundle_ids.access]
  admin = "merchant_read"
  storefront = "public_read"
