export const CURRENCY_SYMBOLS: Record<string, string> = {
    BDT: "৳",
    USD: "$",
    EUR: "€",
    GBP: "£",
    JPY: "¥",
    CAD: "$",
    AUD: "$",
    INR: "₹",
    NZD: "$",
    CHF: "CHF",
    SEK: "kr",
    NOK: "kr",
    DKK: "kr",
    ZAR: "R",
    SGD: "$",
    HKD: "$",
    CNY: "¥",
    KRW: "₩",
    TRY: "₺",
    RUB: "₽",
    BRL: "R$",
    MXN: "$",
    PLN: "zł",
    THB: "฿",
    TWD: "NT$",
    AED: "د.إ",
    SAR: "﷼",
};

export const CURRENCY_LOCALES: Record<string, string> = {
    US: "en-US",
    CA: "en-CA",
    FR: "fr-FR",
    DE: "de-DE",
    GB: "en-GB",
    AU: "en-AU",
    JP: "ja-JP",
    CN: "zh-CN",
    BR: "pt-BR",
    NL: "nl-NL",
    SE: "sv-SE",
    DK: "da-DK",
    NO: "no-NO",
    FI: "fi-FI",
    PL: "pl-PL",
    CZ: "cs-CZ",
    HU: "hu-HU",
    RO: "ro-RO",
    RU: "ru-RU",
    TR: "tr-TR",
    SA: "ar-SA",
    IL: "he-IL",
    TH: "th-TH",
    KR: "ko-KR",
    IN: "hi-IN",
};
